#!/usr/bin/env bash
# SCRIPT: link_launchers.sh
# DESCRIPTION: Create the adrescue launcher, plus the legacy android-rescue-* names.
# USAGE: scripts/link_launchers.sh <install-dir> <bin-dir>
set -euo pipefail

INSTALL_DIRECTORY="${1:-}"
BIN_DIRECTORY="${2:-}"

if [ -z "$INSTALL_DIRECTORY" ] || [ -z "$BIN_DIRECTORY" ]; then
  printf 'Usage: %s <install-dir> <bin-dir>\n' "$0" >&2
  exit 2
fi

mkdir -p "$BIN_DIRECTORY"

WRAPPER_MARKER='# Generated by scripts/link_launchers.sh'

# Git for Windows does not enable symlinks by default: `ln -s` quietly copies
# the file instead. A copy is worse than a failure here, because adrescue
# resolves its own root by following the symlink chain -- with a copy there is
# no chain, ROOT becomes the bin directory, and every "$ROOT/tools/..." lookup
# misses. That is precisely the bug the readlink loop was written to fix,
# arriving back through a different door and only on the platform none of the
# tests can execute.
#
# So the link is verified after it is made, and a real wrapper is written when
# it turns out not to be one.
write_wrapper() {
  local target="$1" link="$2"
  cat >"$link" <<WRAPPER
#!/usr/bin/env bash
$WRAPPER_MARKER
# A symlink would be better. This platform's ln -s copies instead of linking,
# and a copy cannot be followed back to the installation. Re-run the installer
# to point this at a new location.
exec "$target" \${1+"\$@"}
WRAPPER
  chmod +x "$link"
}

link_one() {
  local target="$1" link="$2"
  # ln -sfn replaces a regular file without a word. adrescue is a short, generic
  # name, so something else may legitimately own it; that is the user's binary,
  # not ours to delete. A wrapper this script wrote before is ours, and is
  # replaced: otherwise the second install on Windows refuses every launcher it
  # created during the first.
  if [ -e "$link" ] && [ ! -L "$link" ]; then
    if ! grep -qF "$WRAPPER_MARKER" "$link" 2>/dev/null; then
      printf 'Refusing to replace an existing file: %s\n' "$link" >&2
      return 1
    fi
    rm -f "$link"
  fi

  ln -sfn "$target" "$link" 2>/dev/null || true
  if [ -L "$link" ]; then
    printf '  %s -> %s\n' "$link" "$target"
  else
    write_wrapper "$target" "$link"
    printf '  %s -> %s (wrapper: this platform does not create symlinks)\n' "$link" "$target"
  fi
}

link_one "$INSTALL_DIRECTORY/adrescue" "$BIN_DIRECTORY/adrescue"

# Kept working for anyone who installed before adrescue existed. Undocumented.
for command_name in dump prompt update; do
  link_one "$INSTALL_DIRECTORY/$command_name" "$BIN_DIRECTORY/android-rescue-$command_name"
done
