name: Security

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 5 * * 6"

jobs:
  gitleaks:
    uses: nikolareljin/ci-helpers/.github/workflows/gitleaks-scan.yml@99ff8e3313bd53aede98d8e81fd7afaca4eb9b8b
    with:
      scan_path: "."
      report_format: sarif
      output: results.sarif
      fail_on_findings: true
      upload_artifact: true
